[package]
name = "custom-nosql-cdn"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sha2 = "0.10"
log = "0.4"
env_logger = "0.10"
